window.BOX_SERVER_HOST="http://recipes.foodnetwork.com/";window.BOX_SERVER_S_API="http://dje7rr2pnbe7f.cloudfront.net/public/s/";window.SNI=window.SNI||{};window.SNI.BOX=window.SNI.BOX||{};
window.SNI.BOX.DEBUG=function(){var a=function(){if("undefined"!==typeof console)if(null!==/msie/i.exec(navigator.userAgent)){var a="",d;for(d=0;d<arguments.length;d+=1)0<a.length&&(a+=", "),a="function"===typeof arguments[d]?a+"[function]":"object"===typeof arguments[d]&&"object"===typeof JSON&&"function"===typeof JSON.stringify?a+JSON.stringify(arguments[d]):a+arguments[d].toString();console.log(a)}else try{console.log.apply(null,arguments)}catch(c){console.log(arguments)}},d=!1,n={},c={},b=function(){var d=
"string"===typeof this?this:this instanceof String?this.toString():null;if(b.isEnabled(d)){var c=Array.prototype.slice.call(arguments,0);d&&c.unshift("["+d+"]");a.apply(null,c)}};b.enable=function(a){"string"===typeof a?n[a]=!0:d=!0};b.disable=function(a){"string"===typeof a?n[a]=!1:d=!1};b.isEnabled=function(a){if("string"===typeof a&&null!==a){var f=0<arguments.length&&Array.isArray(arguments[1])?arguments[1]:[];if(-1!==f.indexOf(a))return!1;f.push(a);var h=c[a];return!1!==n[a]&&(!0===n[a]||b.isEnabled(h,
f))}return d||-1!==window.location.hash.indexOf("_debugMrb")};b.forScope=function(a,d){d&&!c[d]&&(c[d]=null);a&&(c[a]=d||null);return function(a){return function(){b.apply(a,arguments)}}(a)};return b}();var EXECUTION=SNI.BOX.DEBUG.forScope("EXECUTION");
(function(a,d){function n(){a.resetTimer&&clearTimeout(a.resetTimer);a.resetTimer=setTimeout(c,100)}function c(){var c=new Date;l.width=a.innerWidth||d.clientWidth;l.height=a.innerHeight||d.clientHeight;l.aspectRatio=l.width/l.height;l.orientation=l.width>l.height?"landscape":"portrait";l.deviceWidth=screen.width;l.deviceHeight=screen.height;l.deviceAspectRatio=l.deviceWidth/l.deviceHeight;l.deviceOrientation=l.deviceWidth>l.deviceHeight?"landscape":"portrait";h();EXECUTION("getMediaFeatures took: "+
(new Date-c)+" ms")}function b(a){return Function("d","return("+a.replace(/\(|\)/g,"").replace(/\s*,\s*/g,") || (").replace(/\s+and\s+/gi," \x26\x26 ").replace(/min-(.*?):/gi,"$1\x3e\x3d").replace(/max-(.*?):/gi,"$1\x3c\x3d").replace(/above-(.*?):/gi,"$1\x3e").replace(/below-(.*?):/gi,"$1\x3c").replace(/min-|max-/gi,"").replace(/(all|screen|print)/,"d.$1").replace(/:/g,"\x3d\x3d").replace(/([\w-]+)\s*([<>=]+)\s*(\w+)/g,function(a,d,c,e){return"d."+q(d)+c+f(e)}).replace(/([<>=]+)([A-z][\w-]*)/g,'$1"$2"')+
")")(l)}function q(a){return a.toLowerCase().replace(/-[a-z]/g,function(a){return a[1].toUpperCase()})}function f(a){return a.replace(/([\d\.]+)(%|em|in|pt|px)/,function(a,c,e){return"em"==e?16*c:"in"==e?96*c:"pt"==e?96*c/72:"%"==e?c/(scope.innerWidth||d.clientWidth):c})}function h(){for(var a=0,k,c,f;k=m[a];++a)if(c=k.media.match(/(.+?):media\((.+?)\)/)){if(d.querySelectorAll){all=d.querySelectorAll(c[1]);for(var h=0;f=all[h];++h){if(/this/.test(c[2])){var g=f.getBoundingClientRect();l.thisWidth=
g.width||g.right-g.left;l.thisHeight=g.height||g.bottom-g.top;l.thisAspectRatio=l.thisWidth/l.thisHeight;l.thisOrientation=l.thisWidth>l.thisHeight?"landscape":"portrait"}0<f.clientWidth&&(b(c[2])?e(f,k.className):r(f,k.className))}}}else 0<f.clientWidth&&(b(k.media)?e(d,k.className):r(d,k.className))}function t(a,k){var d=this,c=1;d.className=a;d.media=k;d.index=m.push(d)-1;d.enable=function(){c||(d.index=m.push(d)-1,c=!0)};d.disable=function(){c&&(m.splice(d.index,1),c=!1)};d.refresh=function(){h()}}
var l={all:!0,screen:!0,print:!1},g=("addEventListener"in a?"addEventListener ":"attachEvent on").split(" "),p=["blur","orientationchange","click"],u=["resize","scroll"],v=0;for(;p[v];++v)a[g[0]](g[1]+p[v],c);for(v=0;u[v];++v)a[g[0]](g[1]+u[v],n);var w=Array.prototype.lastIndexOf||function(a){for(var d=this.length;-1<--d&&this[d]!=a;);return d},e=function(a,d){var c=a.className?a.className.split(/\s+/):[];0>w.call(c,d)&&(a.className=c.concat(d).join(" "))},r=function(a,d){var c=a.className?a.className.split(/\s+/):
[],f=w.call(c,d);-1<f&&c.splice(f,1)&&(a.className=c.join(" "))},m=[];a.MediaClass=function(a,d){var c=new t(a,d);h();return c};c()})(this,document.documentElement);
function EnvironmentContext(a,d,n){var c=this;if("undefined"!==typeof n&&"boolean"!==typeof n)throw Error('IllegalArgumentException: "decoupled" must be a boolean!');n=!0;c.decoupled=n;c.createTime=new Date;c.name=a;c.loaded=!1;c.callbacks=[];c.executeCallback="function"===typeof d?d:function(a){a.call()};c.timerRunning=n;c.timer=setInterval(function(){!0===c.loaded&&(SNI.BOX.DEBUG('Executing "'+c.name+'" callbacks'),c.executeContextLoadedCallbacks())},30);c.createHandler(c.name)}
EnvironmentContext.prototype={getName:function(){return this.name},createHandler:function(a){if("undefined"===typeof a||0===a.length)throw Error("handler name cannot be blank");if("undefined"!==typeof window[a])throw Error("window["+a+"] is already defined");var d=this;window[a]=function(a){"function"===typeof a&&(!0===d.loaded&&!1===d.timerRunning?(SNI.BOX.DEBUG('context.loaded was true, invoking "'+d.name+'" callback immediately'),d.executeCallback.call(null,a)):(!0===d.timerRunning?SNI.BOX.DEBUG('context.timerRunning was true, pushing "'+
d.name+'" callback to queue'):SNI.BOX.DEBUG('context.loaded was false, pushing "'+d.name+'" callback to queue'),d.callbacks.push(a)))}},getHandler:function(){return window[this.name]},setContextLoaded:function(){this.loaded=!0;!1===this.decoupled&&this.executeContextLoadedCallbacks()},executeContextLoadedCallbacks:function(){var a;clearInterval(this.timer);for(a=0;a<this.callbacks.length;a+=1)SNI.BOX.DEBUG('Executing "'+this.name+'" callback from queue position '+a),this.executeCallback.call(null,
this.callbacks[a]);this.timerRunning=!1;this.callbacks=[]}};
(function(a,d){a.SNI=a.SNI||{};a.SNI.BOX=a.SNI.BOX||{};a.SNI.BOX.$LAB===d&&function(){(function(a){function d(a,c){var k=/^\w+\:\/\//;/^\/\/\/?/.test(a)?a=location.protocol+a:k.test(a)||"/"==a.charAt(0)||(a=(c||"")+a);return k.test(a)?a:("/"==a.charAt(0)?r:e)+a}function b(a,d){for(var c in a)a.hasOwnProperty(c)&&(d[c]=a[c]);return d}function q(a,d,c,k){a.onload=a.onreadystatechange=function(){a.readyState&&"complete"!=a.readyState&&"loaded"!=a.readyState||d[c]||(a.onload=a.onreadystatechange=null,
k())}}function f(a){a.ready=a.finished=!0;for(var d=0;d<a.finished_listeners.length;d++)a.finished_listeners[d]();a.ready_listeners=[];a.finished_listeners=[]}function h(a,d,c,k,f){setTimeout(function(){var e,h=d.real_src,b;if("item"in m){if(!m[0]){setTimeout(arguments.callee,25);return}m=m[0]}e=document.createElement("script");d.type&&(e.type=d.type);d.charset&&(e.charset=d.charset);f?E?(c.elem=e,M?(e.preload=!0,e.onpreload=k):e.onreadystatechange=function(){"loaded"==e.readyState&&k()},e.src=h):
f&&0==h.indexOf(r)&&a[g]?(b=new XMLHttpRequest,b.onreadystatechange=function(){4==b.readyState&&(b.onreadystatechange=function(){},c.text=b.responseText+"\n//@ sourceURL\x3d"+h,k())},b.open("GET",h),b.send()):(e.type="text/cache-script",q(e,c,"ready",function(){m.removeChild(e);k()}),e.src=h,m.insertBefore(e,m.firstChild)):(z&&(e.async=!1),q(e,c,"finished",k),e.src=h,m.insertBefore(e,m.firstChild))},0)}function t(){function k(a,d,c){function e(){null!=A&&(A=null,f(c))}var A;K[d.src].finished||(a[u]||
(K[d.src].finished=!0),A=c.elem||document.createElement("script"),d.type&&(A.type=d.type),d.charset&&(A.charset=d.charset),q(A,c,"finished",e),c.elem?c.elem=null:c.text?(A.onload=A.onreadystatechange=null,A.text=c.text):A.src=d.real_src,m.insertBefore(A,m.firstChild),c.text&&e())}function e(a,b,r,g){var A,m,L=function(){b.ready_cb(b,function(){k(a,b,A)})},l=function(){b.finished_cb(b,r)};b.src=d(b.src,a[w]);b.real_src=b.src+(a[v]?(/\?.*$/.test(b.src)?"\x26_":"?_")+~~(1E9*Math.random())+"\x3d":"");
K[b.src]||(K[b.src]={items:[],finished:!1});m=K[b.src].items;a[u]||0==m.length?(A=m[m.length]={ready:!1,finished:!1,ready_listeners:[L],finished_listeners:[l]},h(a,b,A,g?function(){A.ready=!0;for(var a=0;a<A.ready_listeners.length;a++)A.ready_listeners[a]();A.ready_listeners=[]}:function(){f(A)},g)):(A=m[0],A.finished?l():A.finished_listeners.push(l))}function r(){function a(d,k){d.ready=!0;d.exec_trigger=k;c()}function d(a,k){a.ready=a.finished=!0;a.exec_trigger=null;for(var e=0;e<k.scripts.length;e++)if(!k.scripts[e].finished)return;
k.finished=!0;c()}function c(){for(;g<h.length;)if("[object Function]"==Object.prototype.toString.call(h[g]))try{h[g++]()}catch(a){}else{if(!h[g].finished){for(var d=h[g],k=!1,e=0;e<d.scripts.length;e++)d.scripts[e].ready&&d.scripts[e].exec_trigger&&(k=!0,d.scripts[e].exec_trigger(),d.scripts[e].exec_trigger=null);if(k)continue;break}g++}g==h.length&&(H=m=!1)}var k,f=b(x,{}),h=[],g=0,m=!1,H;k={script:function(){for(var c=0;c<arguments.length;c++){var g=arguments[c],r=arguments[c],l=void 0;"[object Array]"==
Object.prototype.toString.call(g)||(r=[g]);for(var L=0;L<r.length;L++)H&&H.scripts||h.push(H={scripts:[],finished:!0}),g=r[L],"[object Function]"==Object.prototype.toString.call(g)&&(g=g()),g&&("[object Array]"==Object.prototype.toString.call(g)?(l=[].slice.call(g),l.unshift(L,1),[].splice.apply(r,l),L--):("string"==typeof g&&(g={src:g}),g=b(g,{ready:!1,ready_cb:a,finished:!1,finished_cb:d}),H.finished=!1,H.scripts.push(g),e(f,g,H,M&&m),m=!0,f[p]&&k.wait()))}return k},wait:function(){if(0<arguments.length){for(var a=
0;a<arguments.length;a++)h.push(arguments[a]);H=h[h.length-1]}else H=!1;c();return k}};return{script:k.script,wait:k.wait,setOptions:function(a){b(a,f);return k}}}var x={},M=E||B,z=[],K={},J;x[g]=!0;x[p]=!1;x[u]=!1;x[v]=!1;x[w]="";return J={setGlobalDefaults:function(a){b(a,x);return J},setOptions:function(){return r().setOptions.apply(null,arguments)},script:function(){return r().script.apply(null,arguments)},wait:function(){return r().wait.apply(null,arguments)},queueScript:function(){z[z.length]=
{type:"script",args:[].slice.call(arguments)};return J},queueWait:function(){z[z.length]={type:"wait",args:[].slice.call(arguments)};return J},runQueue:function(){for(var a=J,d=z.length,c;0<=--d;)c=z.shift(),a=a[c.type].apply(null,c.args);return a},noConflict:function(){a.$LAB=l;return J},sandbox:function(){return t()}}}var l=a.$LAB,g="UseLocalXHR",p="AlwaysPreserveOrder",u="AllowDuplicates",v="CacheBust",w="BasePath",e=/^[^?#]*\//.exec(location.href)[0],r=/^\w+\:\/\/\/?[^\/]+/.exec(e)[0],m=document.head||
document.getElementsByTagName("head"),x=a.opera&&"[object Opera]"==Object.prototype.toString.call(a.opera)||"MozAppearance"in document.documentElement.style,k=document.createElement("script"),M="boolean"==typeof k.preload,E=M||k.readyState&&"uninitialized"==k.readyState,z=!E&&!0===k.async,B=!E&&!z&&!x;a.$LAB=t();(function(a,d,c){null==document.readyState&&document[a]&&(document.readyState="loading",document[a](d,c=function(){document.removeEventListener(d,c,!1);document.readyState="complete"},!1))})("addEventListener",
"DOMContentLoaded")})(this)}.call(a.SNI.BOX)})(window,void 0);
(function(a,d){a.SNI.BOX.$LAB===d||a.SNI!==d&&a.SNI.BOX!==d&&a.SNI.BOX.LOADED!==d?SNI.BOX.DEBUG("LAB.js script loader could not be found!"):function(n){a.SNI=a.SNI||{};a.SNI.BOX=a.SNI.BOX||{};a.SNI.BOX.LOADED=!0;var c=SNI.BOX.DEBUG.forScope("CORE"),b=SNI.BOX.DEBUG.forScope("AUTH","CORE"),q=SNI.BOX.DEBUG.forScope("RENDER","CORE"),f=SNI.BOX.DEBUG.forScope("EXECUTION","CORE");"function"!==typeof String.prototype.startsWith&&(String.prototype.startsWith=function(a){return 0===this.lastIndexOf(a,a.length-
1)});"function"!==typeof String.prototype.endsWith&&(String.prototype.endsWith=function(a){return-1!==this.indexOf(a,this.length-a.length)});var h=/^((?:(https?):)?(?:\/\/)?([^\/:]+)(?::\d+)?)/,t=/(?:[^.]+\.)*([^.]+\.[^.]+)$/,l=function(a){a=h.exec(a);a=null==a||4>a.length?null:a[3];if(null===a)return null;a=t.exec(a);return null==a||2>a.length?null:a[1]},g=function(a){a=/^(?:(https?):)?(?:\/\/)?(([^\/:]+)(:\d+)?)/.exec(a);return null===a||3>a.length?null:a[2]},p=function(a){a=h.exec(a);return null===
a?null:a[1]},u=function(c){if(c===d||null===c)throw Error("url cannot be blank");c=h.exec(c);var e=h.exec(a.location);if(null===c||null===e)return!1;var b=c[3],f=e[3];return c[2]!==e[2]||b!==f},v=function(){(function(k){c("Using jQuery version: "+k.fn.jquery);var e=[{url:"/js/mediaclass.js",shouldLoad:function(){return"function"!==typeof a.MediaClass}}],h={},r=function(a,e){var b,f,g,r=[];if(e instanceof Array)for(b=0;b<e.length;b+=1){if("string"!==typeof e[b].url)throw Error('"url" field of script dependency is required');
if("function"===typeof e[b].shouldLoad&&!0!==e[b].shouldLoad.call(null)||h[e[b].url]!==d){if(h[e[b].url]!==d)return c("Already Loading script dependency ["+f+"]"),h[e[b].url];c("Skipping script dependency ["+e[b].url+"]")}else g=p(e[b].url),f=null===g?0===e[b].url.indexOf("/")&&a.endsWith("/")?a+e[b].url.substr(1):a+e[b].url:e[b].url,c("Loading script dependency  ["+f+"]"),function(){var a=new k.Deferred;r.push(a);h[e[b].url]=a;n.queueScript(""+f).queueWait(function(){a.resolve()})}();0<r.length&&
n.runQueue()}return k.when.apply(null,r).pipe(function(){c("All script dependencies loaded.")})},m={},t=function(a,d){var e,b,f;if(d instanceof Array)for(e=0;e<d.length;e+=1){if("string"!==typeof d[e].url)throw Error('"url" field of style dependency is required');"function"===typeof d[e].shouldLoad&&!0!==d[e].shoudlLoad.call(null)||!0===m[d[e].url]?c("Skipping style dependency ["+b+"]"):(m[d[e].url]=!0,b=p(d[e].url),b=null===b?0===d[e].url.indexOf("/")&&a.endsWith("/")?a+d[e].url.substr(1):a+d[e].url:
d[e].url,0<k('link[rel\x3d"stylesheet"][href\x3d"'+b+'"]').size()||(f=/\.less$/.test(b),f=k("\x3clink /\x3e",{rel:f?"stylesheet/less":"stylesheet",type:f?"stylesheet/less":"text/css",href:b}),c("Loading style dependency ["+b+"]"),k("head").append(f)))}},x=function(a,d){if("string"!==typeof d||!a)return null;d=d.trim().trim();if(0===d.length)return null;var c=d.split("/"),e,b=a;for(e=0;e<c.length;e+=1){var k=c[e];if("object"!==typeof b)return null;if(!1===b.hasOwnProperty(k))if(/^\d+$/.test(k))k=parseInt(k,
10),Array.isArray(b)&&0<=k&&k<b.length&&(b=b[k]);else return null;else b=b[k]}return b},v=function(a,c,e,b,h,g){var r=k(this),m,l,p,t,n=k(a),x=function(a,d){var e=k(d),f=null===c?F(e):c;m.callback.apply(e,[f,b,h,g])},u=new Date;for(a=0;a<e.length;a+=1){m=e[a];var v=new Date;t=p=l=null;m.type!==d&&(l=n.find('[itemtype~\x3d"'+m.type+'"]').add(n.filter('[itemtype~\x3d"'+m.type+'"]')),0===l.size()?(t=r.closest('[itemscope][itemtype~\x3d"'+m.type+'"]'),0<t.size()&&m.prop!==d&&(p=n.find('[itemprop\x3d"'+
m.prop+'"]').add(n.filter('[itemprop\x3d"'+m.prop+'"]')))):m.prop!==d&&(p=l.find('[itemprop\x3d"'+m.prop+'"]')));m.prop!==d&&null!==p&&null!==p&&0<p.size()?(q("RENDER: [type/prop:"+m.type+"/"+m.prop+"]",p,m.callback),p.each(x)):m.prop===d&&m.type!==d&&null!==l&&0<l.size()?(q("RENDER: [type:"+m.type+"]",l,m.callback),l.each(x)):m.prop===d&&m.type!==d&&null!==t&&0<t.size()?(q("RENDER: [type:"+m.type+"]",t,m.callback),t.each(x)):m.prop===d&&m.type===d&&(q("RENDER: [module]",n,m.callback),m.callback.apply(n,
[c,b,h,g]));10<new Date-v&&f("Applying renderer: ",m," took: "+(new Date-v)+" ms")}f("Applying all renderers took: "+(new Date-u)+" ms")},w=function(a,c){var e="boolean"===typeof c?c:!1,b=k(a),f=b.attr("itemtype").split(/\s+/),h={},m={},g=!1,r=b.filter("[itemprop]").add(b.find("[itemprop]")),l=b.attr("itemref");l!==d&&k("#"+l.split(" ").join(",#")).each(function(){var a=k(this),d=a.filter("[itemprop]");0===d.size()&&(d=a.find("[itemprop]"));d.data("itemRef",a);r.add(d)});r.each(function(){var a=k(this),
e,f,r,l;l=" "+a[0].tagName.toLowerCase()+" ";e=a.parent().closest("[itemscope]");r=(f=a.data("itemRef"))?k('[itemref~\x3d"'+f[0].id+'"]'):null;if(!1===a.is(b)&&(!0===e.is(b)&&!r||r&&r.is(b)&&!k.contains(f[0],r[0]))&&(g=!0,a.is("[itemscope]")?l=w(a,c):-1!==" meta ".indexOf(l)?l=k.trim(a.attr("content")):-1!==" audio embed iframe img source track video ".indexOf(l)?l=k.trim(a.attr("src")):-1!==" a area link ".indexOf(l)?l=k.trim(a.attr("href")):-1!==" object ".indexOf(l)?l=k.trim(a.attr("data")):-1!==
" data meter ".indexOf(l)?(l=k.trim(a.attr("datetime")),l=l===d?k.trim(a.text()):l):l=-1!==" input select textarea ".indexOf(l)?a.val():k.trim(a.text()),e=a.attr("itemprop"),e!==d&&0<k.trim(e).length))for(f=e.split(/\s+/),r=0;r<f.length;r+=1)e=k.trim(f[r]),m[e]===d&&(m[e]=[]),m[e].push(a[0]),""!==l&&(h[e]===d&&(h[e]=[]),h[e].push(l))});var l={},p=b.attr("itemid");!0===g&&(l.properties=h);0<f.length&&(l.types=f);p!==d&&(l.id=p);!0===e&&(l._DOMrefs=m);return l},F=function(a,d){var c=k(a),e=[],b=c.filter("[itemscope]").add(c.find("[itemscope][itemprop]").not(c.find("[itemscope] [itemscope][itemprop]")).not(c.filter("[itemscope]").find("[itemscope][itemprop]")));
0===b.size()&&(b=b.add(c.closest("[itemscope]")));b.each(function(){var a=k(this),b=a.parent().closest("[itemscope]");0!==b.size()&&!1!==k.contains(c,b)||e.push(w(a,d))});return e},U=function(a,c){if(a===d||null===a)throw Error("dataType cannot be blank");if(!0===c)return"jsonp";if("html"===a)return null;if("json"===a)return"json";throw Error('Unrecognized dataType: "'+a+'"');},K=function(a,c){if(a===d||null===a)throw Error("dataType cannot be blank");return!0===c&&"html"===a?"html":null},J=function(a,
c){var e="";a!==d&&null!==a&&(e+="_format\x3d"+a);c!==d&&null!==c&&(0<e.length&&(e+="\x26"),e+="_result\x3d"+c);return e},Q=function(a,c,e,b,h){var m=new Date,g=k(this),r;r=!0===b.reRender?g:k("\x3cdiv /\x3e");var l,p;"string"===typeof a?(p=new Date,a=a.replace(/^(?:.|[\r\n])*?<body[^>]*>/ig,""),a=a.replace(/<\/body>(?:.|[\r\n])*?$/ig,""),r.append(a),l=null,f("processing frame response took: "+(new Date-p)+" ms"),p=new Date,0<c.length&&r.children().each(function(){v.apply(g,[k(this),l,c,e,b,h])}),
f("applying all renderers to all children took: "+(new Date-p)+" ms")):a.status!==d&&"ok"===a.status&&"string"===typeof a.result?(p=new Date,a=a.result,a=a.replace(/^(?:.|[\r\n])*?<body[^>]*>/ig,""),a=a.replace(/<\/body>(?:.|[\r\n])*?$/ig,""),r.append(a),l=null,f("processing frame response took: "+(new Date-p)+" ms"),p=new Date,0<c.length&&r.children().each(function(){v.apply(g,[k(this),l,c,e,b,h])}),f("applying all renderers to all children took: "+(new Date-p)+" ms")):a.status!==d&&"ok"===a.status&&
"object"===typeof a.result?(l=a.result,0<c.length&&v.apply(g,[r,l,c,e,b,h])):"object"===typeof a&&(l=a,0<c.length&&v.apply(g,[r,l,c,e,b,h]));p=new Date;r.find("[data-box-module-name]").each(function(){var a=k(this);if(0<a.parent().closest("[data-box-module-name]").size()){var c=a.data("boxModuleName"),e=a.data("boxModuleUrl");k.fn[c]!==d&&k.fn[c].call(a,k.extend(!0,{},b,{url:e}))}});f("nested module processing took: "+(new Date-p)+" ms");f("renderModule took: "+(new Date-m)+" ms");return r.children()},
O=function(a,d,c,e,b){a=k(a);var f=a.data("boxPlugin");a.filter(".dari-frame").add(a.find(".dari-frame")).each(function(){var a=k(this);f&&f.options().jsonp&&(a.attr("data-jsonp-callback-param",f.options().jsonp),f.options().jsonpCallback&&a.attr("data-jsonp-callback",f.options().jsonpCallback));a.attr("data-ajax-data-type",d);a.attr("data-ajax-result-type",c);a.attr("data-source-data-format",e);a.attr("data-auth-scheme",b)});return null},R={events:{beginLoad:function(a,d){var c=SNI.BOX.AUTH.getSchemeByName(a.$frame.attr("data-auth-scheme"));
if(null!==c){var e=a.$frame.attr("data-extra-form-data"),c=e?c.signUrl(c.unSignUrl("?"+e)).substring(1):c.signUrl("?").substring(2);a.$frame.attr("data-extra-form-data",c)}}},setBody:function(a){var e=new Date,b=k(this),h=b.data("ajaxDataType"),m=b.data("ajaxResultType"),r=b.data("sourceDataFormat"),g=b.data("authScheme"),l=b.is(".mrb-module")?b:b.closest(".mrb-module");c("frame.js / setBody, $frame: ",b,", $module: ",l);var l=l.data("boxPlugin"),p=b.data("source"),t=new k.Deferred;a=Q.apply(b,[a,
l.rendererList(),l,l.options(),t]);O(a,h,m,r,g);h=p!==d&&null!==p&&p.hasClass("mrb-frame-append");if(!1!==h||!0!==l.options().reRender)h?(p.remove(),b.append(a)):b.html(a);f("frame.setBody took: "+(new Date-e)+" ms");e=new Date;t.resolve();f("resolving renderCompleteDfd took: "+(new Date-e)+" ms")}},G={};k.extend(!0,a.SNI,{BOX:{Util:{isCrossDomain:u,schemaToJson:F,getUrlPrefix:p,getDomain:l,getHost:g,loadStyles:t,loadScripts:r,getByPath:x,updateByPath:function(a,e,b){a=k(a);0!==a.size()&&a.each(function(){var a=
k(this),f=F(a,!0);0===e.indexOf("/")&&(e=e.substring(1));0!==e.indexOf("0/")&&(e="0/"+e);a=e.lastIndexOf("/properties");if(-1!==a){var h=e.substr(0,a),a=e.substr(h.length+11+1),f=x(f,h);if("object"===typeof f){f=x(f,"_DOMrefs/"+a);if(f!==d&&null!==f){var h=k(f),m=" "+k.trim(h[0].tagName.toLowerCase())+" ";-1!==" meta ".indexOf(m)?h.attr("content",b):-1!==" audio embed iframe img source track video ".indexOf(m)?h.attr("src",b):-1!==" a area link ".indexOf(m)?h.attr("href",b):-1!==" object ".indexOf(m)?
h.attr("data",b):-1!==" data meter ".indexOf(m)?h.is("[datetime]")?h.attr("datetime",b):h.text(b):-1!==" input select textarea ".indexOf(m)?(b?h.val(b):h.val(""),h.val(b)):b?h.text(b):h.text("")}c("modifying ["+a+"] on ",f," setting to ["+b+"]")}}})},appendParam:function(a,d,c){d=encodeURIComponent(d)+"\x3d"+encodeURIComponent(c);d=-1===a.indexOf("?")?"?"+d:"\x26"+d;return a+d},removeParam:function(a,d){var c=SNI.BOX.Util.removeHash(a).split("?");if(2<=c.length){for(var e=SNI.BOX.Util.getHash(a),
b=encodeURIComponent(d)+"\x3d",f=c[1].split(/[&;]/g),h=f.length;0<h--;)-1!==f[h].lastIndexOf(b,0)&&f.splice(h,1);a=c[0];0<f.length&&(a+="?"+f.join("\x26"));null!==e&&(a+="#"+e)}return a},getHash:function(a){var d=a.indexOf("#1");return-1!==d?a.substr(d):null},removeHash:function(a){var d=a.indexOf("#");return-1!==d?a.substr(0,d):a},getQueryParamByName:function(){var a={},c=/\+/g,e=/([^&=]+)=?([^&]*)/g;return function(b,f){if(a[b]===d){var h;h=b.indexOf("?");for(var k=-1===h?"":b.substr(h+1),m={};h=
e.exec(k);)m[decodeURIComponent(h[1].replace(c," "))]=decodeURIComponent(h[2].replace(c," "));a[b]=m}return a[b][f]!==d?a[b][f]:null}}()},RESPONSIVE_CLASS:"mrb-responsive",addElementQuery:function(c,e){if(c===d||0===c.length||e===d||0===e.length)throw Error("Usage: plugin.addElementQuery(className, predicate)");if(G[c]!==d)throw Error('element query with name "'+c+'" already exists!  Use plugin.removeElementQuery(className) first!');G[c]=new MediaClass(c,"."+a.SNI.BOX.RESPONSIVE_CLASS+":"+e)},removeElementQuery:function(a){if(a===
d||0===a.length)throw Error("Usage: plugin.removeElementQuery(className)");G[a]!==d&&delete G[a]},getElementQuery:function(a){if(a===d||0===a.length)throw Error("Usage: plugin.getElementQuery(className)");return G[a]},fontLoaded:function(){var a;if(arguments[0]instanceof Array)a=arguments[0];else if(0<arguments.length)a=Array.prototype.slice.call(arguments,0);else throw Error("A font name or array of font names is required");var d=[],e;for(e=0;e<a.length;e+=1)(function(){var c=new k.Deferred,b=a[e];
d.push(c);k("body").fontChecker({font:b,load:function(){c.resolve()}})})();return k.when.apply(null,d).pipe(function(){c("All fonts loaded")})},autoRun:function(e,b,f,h){if("string"!==typeof e&&"object"!==typeof e||"string"!==typeof b||"string"!==typeof f)throw Error("Invalid Syntax.  Usage: SNI.BOX.autoRun(moduleId, moduleName, moduleClass, params");var m="string"===typeof e?k("#"+e):k(e);if(0===m.size())c("Could not find module with id: "+e);else{if(k.fn[b]!==d)c("$.fn.["+b+"] :: Auto-invoking plugin for id\x3d"+
e+", class\x3d"+f),k.fn[b].call(m,h);else{var r={};r[e]=SNI.BOX.plugin(h,function(){c("SNI.BOX.Anon :: Auto-invoking module based on class\x3d"+f)});k.extend(!0,a.SNI.BOX,{Anon:r});c("SNI.BOX.Anon :: Register plugin for id\x3d",e,", class\x3d"+f);SNI.BOX.Anon[e].call(m,{})}k("body").addClass(b)}},authenticatedPlugin:function(a,d,c){return k.plugin(k.extend(!0,{},{authSchemeName:null},a),function(a,e){var f=k(this);f.data("boxAuthPlugin",a);b("entering authenticatedPlugin's init method");var h=null,
m=null,r=null,g=null,l=null,p="string"===typeof e.authSchemeName?SNI.BOX.AUTH.getSchemeByName(e.authSchemeName):SNI.BOX.AUTH.getFirstScheme();if(null===p){if("string"===typeof e.authSchemeName)throw Error('No auth scheme named "'+e.authSchemeName+'" has been registered!');throw Error("No auth scheme has been registered!");}a.getAuthScheme=function(){return p};p.onReady(function(){a.authenticate=function(d,g){var t=null===m;if(!0!==l){b("calling plugin.authenticate");"boolean"!==typeof d&&(d=!1);if(!0!==
p.isAuthenticated())throw Error("No authentication detected, cannot load authenticated state");l=!0;!0===t&&(b("initializing authModule"),m=h);b("inserting $authModule",m,"after $unAuthRoot",r);r.after(m);!0===t?c.apply(m,[a,e,d,g]):m.trigger("box.authenticate",[a,e,d,g]);m.show();r.detach();!0===e.isPopup&&(b("removing click handler to require login on ",f),f.off("click",p.requireLogin));k(p).one("logout",function(e,d,c){b("heard logout event");a.unAuthenticate()})}else b("plugin.authenticate was called on an already-authenticated state!")};
a.unAuthenticate=function(){var c=null===g;!1!==l?(l=!1,b("calling plugin.unAuthenticate"),!0===c&&(b("initializing unAuthModule"),g=r),b("inserting $unAuthModule",g,"after $authRoot",h),h.after(g),!0===c?d.apply(g,[a,e]):g.trigger("box.unauthenticate",[a,e]),g.show(),h.detach(),!0===e.isPopup&&(b("instantiating click handler to require login on ",f),f.on("click",p.requireLogin)),k(p).one("login",function(e,d,c){b("heard login event");a.authenticate(!0,c)})):b("plugin.unAuthenticate was called on an already-unauthenticated state!")};
!0===p.isAuthenticated()?(h=f,r=f.clone(!0,!0).hide(),f.after(r),a.authenticate(!1)):(r=f,h=f.clone(!0,!0).hide(),f.after(h),a.unAuthenticate(),!0===e.isPopup&&!0===e.startOpen&&p.requireLogin())})})},plugin:function(b,h){var m=[],g=k.plugin(k.extend(!0,{},{url:null,errorClass:"mrb-error",loadedClass:"box-loaded",eventNamespace:"mrb-events",scriptDependencies:[],styleDependencies:[],requiredFonts:[],dataType:"html",sourceDataFormat:"html",jsonp:"_callback",syncDataLoad:null,isPopup:!1,startOpen:!1,
popupOptions:{},cache:!1,initData:null,authSchemeName:null},b),function(b,f){var g=k(this);g.data("boxPlugin",b);var l=new k.Deferred,q=!0;b.firstRender=function(){return q};b.ready=b.dfd=function(){return l};b.ready().then(function(){g.trigger("pluginReady",[b,f])});b.rendererList=function(){return m};b.options=function(){return f};b.element=function(){return g};b.moduleRoot=function(){var a=g.filter("[data-box-module-name]");0===a.size()&&(a=g.find("[data-box-module-name]"));return a};var n=!1,
x=new k.Deferred;f.requiredFonts instanceof Array&&0<f.requiredFonts.length?x=SNI.BOX.fontLoaded(f.requiredFonts):x.resolve();var w=e.slice(0);f.scriptDependencies instanceof Array&&0<f.scriptDependencies.length&&(w=w.concat(f.scriptDependencies));var B=null===f.url?null:p(f.url);null===B&&(B=a.BOX_SERVER_S_API?p(a.BOX_SERVER_S_API):p(a.location.href));var y=!0!==f.cors&&null!==f.url&&u(f.url),A=U(f.dataType,y),E=K(f.dataType,y),D=f.url;null!==D&&"html"===f.sourceDataFormat&&(y=J(A,E),0<y.length&&
(D+=-1!==f.url.indexOf("?")?"\x26":"?",D+=y));var G=function(a,e){a.addClass("mrb-module");a.data("boxPlugin",b);a.trigger("boxPluginBeginLoad",[b,f]);t(B,f.styleDependencies);r(B,w).then(function(){if(null!==f.initData&&void 0!==f.initData||f.url===d||null===f.url)"object"===typeof f.initData&&x.then(function(){var d=new k.Deferred,c=Q.apply(a,[f.initData,m,b,f,d]);!0!==b.options().reRender&&a.html(c);d.resolve();q=!1;!1===n&&("function"===typeof h&&h.apply(a,[b,f]),n=!0);a.frame(R);O(a,A,E,f.sourceDataFormat,
f.authSchemeName);e.resolve()}).fail(function(){c("Required fonts could not be loaded!");e.fail()});else if(!1===a.hasClass(f.loadedClass)){var g={cache:f.cache,jsonp:f.jsonp};f.jsonpCallback&&(g.jsonpCallback=f.jsonpCallback);k.ajax(k.extend(!0,{},g,{url:D,dataType:A,success:function(d){x.then(function(){var c=new k.Deferred,g=Q.apply(a,[d,m,b,f,c]);!0!==b.options().reRender&&a.html(g);c.resolve();q=!1;!1===n&&("function"===typeof h&&h.apply(a,[b,f]),n=!0);a.frame(R);O(a,A,E,f.sourceDataFormat,f.authSchemeName);
e.resolve()}).fail(function(){c("Required fonts could not be loaded!");e.fail()})},error:function(){c("ERROR: ajax call to module data URL failed");e.fail()}}))}else x.then(function(){var d=new k.Deferred;0<m.length&&v.apply(a,[a,f.initData,m,b,f,d]);d.resolve();q=!1;!1===n&&("function"===typeof h&&h.apply(a,[b,f]),n=!0);a.frame(R);O(a,A,E,f.sourceDataFormat,f.authSchemeName);e.resolve()}).fail(function(){c("Required fonts could not be loaded!");e.fail()})})},S=!1,P;if(!0===f.isPopup){c("adding popup functionality");
var T=k("\x3cdiv /\x3e"),N=null;c("original $element before moving into popup: ",g);!1===g.hasClass(f.loadedClass)&&(N=g,g=k("\x3cdiv /\x3e"));T.append(g);c("moving $element into popup: ",g);k(document.body).append(T);c("piping plugin.dfd()");P=b.dfd().pipe(function(){c("inside the pipe with popupOptions: ",f.popupOptions);f.popupOptions.name!==d&&g.attr("name",f.popupOptions.name);g.popup(f.popupOptions);g.popup("source",N);T.remove();c("setting popup source to",N)});b.open=function(a,e){c("calling plugin.open");
!1===S?(S=!0,G(g,l),P.then(function(){c("opening popup from plugin.open");g.trigger("open.popup")})):(c("opening popup from plugin.open (direct)"),g.trigger("open.popup"),a!==d&&g.popup("source",g,e))};b.close=function(){P.isResolved()&&g.trigger("close.popup")};if(null!==N)N.on("click",function(a){a.preventDefault();b.open()})}g.on("click","[data-action]",function(a){var e=k(this),f=e.attr("data-action");if(f!==d&&0<f.length){a.preventDefault();a.stopPropagation();a=e.parent().closest("[itemscope]");
var h={};if(g.is(a)||k.contains(g[0],a[0]))h=F(a);var m=e.data("actionData");c("Triggering action: "+f+" on ",a);b.trigger(f,m,h,e);a.trigger(f,[m,h,e])}});!0===f.isPopup?!0===f.startOpen&&(c("found startOpen \x3d\x3d\x3d true"),S=!0,G(g,l),P.then(function(){c("opening popup");g.trigger("open.popup")})):(c("skipping popup functionality"),G(g,l))});g.addRenderer=function(){q("RENDER: adding renderer:",arguments);var a={};if("function"===typeof arguments[0])a.callback=arguments[0];else if("function"===
typeof arguments[1])a.type=arguments[0],a.callback=arguments[1];else if("function"===typeof arguments[2])a.type=arguments[0],a.prop=arguments[1],a.callback=arguments[2];else throw Error("Syntax error.  Usage: addRenderer([type,] [prop,] callback)");m.push(a)};g.addRenderer(function(e,c,b){var f=k(this).filter("[data-box-module-name]").add(k(this).find("[data-box-module-name]"));f.each(function(){!1===f.hasClass(a.SNI.BOX.RESPONSIVE_CLASS)&&f.addClass(a.SNI.BOX.RESPONSIVE_CLASS)});a.SNI.BOX.getElementQuery("mrb-smart-phone")===
d&&a.SNI.BOX.addElementQuery("mrb-smart-phone","media(this-max-width:768px)");SNI.BOX.getElementQuery("mrb-tablet")===d&&a.SNI.BOX.addElementQuery("mrb-tablet","media(this-min-width: 768px \x26\x26 this-max-width: 1024px)")});g.addRenderer(function(e,b,h,g){g.then(function(){b.dfd().then(function(){var e=new Date;if(!0===h.isModal)if(k.fn.modal!==d){var g=k("#box-modal-container");0===g.size()&&(g=k("\x3cdiv /\x3e",{id:"box-modal-container","class":"modal"}),k("body").append(g));!1===g.parent().is("body")&&
k("body").append(g);if(!1===h.addModalContainer)k.contains(g[0],b.element()[0])||(b.element().detach(),g.empty(),g.append(b.element()));else{var m=h.modalSize?h.modalSize:"modal-md",r=g.find(".modal-content");if(0===r.size()){var l=k("\x3cdiv /\x3e",{"class":"modal-dialog "+m}),r=k("\x3cdiv /\x3e",{"class":"modal-content"});g.append(l);l.append(r)}else l=r.parent(),l.removeClass(),l.addClass("modal-dialog"),l.addClass(m);g.children().not(l).remove();k.contains(r[0],b.element()[0])||(b.element().detach(),
r.empty(),r.append(b.element()));m=r.find(".modal-close");0===m.size()&&(m=k("\x3cdiv /\x3e",{"class":"modal-close"}));0<g.nextAll(".modal").size()&&k("body").append(g)}g.modal("show");m=g.data("bs.modal");c("backdrop: ",m.$backdrop);var p=m.$backdrop;p.attr("id","box-modal-backdrop");var t=k("\x3cdiv/\x3e",{id:"backdrop-placeholder"});t.insertBefore(p);g.one("hide.bs.modal",function(){c("heard hide.bs.modal");0<t.size()&&(p.insertAfter(t),t.remove())});p.insertBefore(g);g=g.children().first();m=
g.height();r=a.innerHeight;g.css({"margin-top":m>=r||!0===a.SNI.BOX.Util.isMobile()?0:(r-m)/2})}else c("Could not find $.fn.modal!");f("modal renderer took: "+(new Date-e)+" ms")})})});g.addRenderer(function(a,e,d,b){e.dfd().then(function(){b.then(function(){var d=new Date;if(null!==a&&"object"===typeof a&&"object"===typeof a.events&&Array.isArray(a.events)){var b;for(b=0;b<a.events.length;b+=1){var g=a.events[b],h=g.name,g=g.data;c("Triggering event ["+h+"], on: ",e.element(),", data: ",g);try{e.element().trigger(h,
[g])}catch(m){c("Caught exception while triggering event: ",m)}}}f("ajax event renderer took: "+(new Date-d)+" ms")})})});g.addRenderer("com.scrippsnetworks.box.Event",function(a,e,b,g){var h=k(this);e.dfd().then(function(){g.then(function(){var e=new Date;if(a!==d&&Array.isArray(a)){var b;for(b=0;b<a.length;b+=1){var g=a[b].properties,m=g.name[0],r;g.data&&"string"===typeof g.data[0]&&(r=JSON.parse(k("\x3cdiv /\x3e").html(g.data[0]).text()));Array.isArray(g.errors);c("Triggering event ["+m+"], on: ",
h,", data: ",r);try{h.trigger(m,[r])}catch(l){c("Caught exception while triggering event: ",l)}}}f("schema event renderer took: "+(new Date-e)+" ms")})})});g.addRenderer(function(a,e,d){a=k(this);0===a.parent().closest(".mrb-style").size()&&a.addClass("mrb-style")});return g}}});k(function(){k("body").on("redirect",function(e,d){c("entering handler for [redirect]");a.location=d.url}).on("closeModal",function(){var a=k("#box-modal-container");c("module.js: closing modal");a.modal("hide")}).on("alertMessage",
function(e,d){a.SNI.BOX.Util.alert(d)})})})(a.SNI.BOX.jQuery)},w=new EnvironmentContext("boxContextLoaded",function(a){a.call(null,SNI.BOX.jQuery)}),e=a.jQuery===d,r=!e;if(r){r=a.jQuery.fn.jquery;c("Found jQuery version "+r);var m=r.split("."),r=parseInt(m[0],10),x=parseInt(m[1],10),m=2<m.length?parseInt(m[2],10):0,r=1===r&&8===x&&3===m}!1===r?n.script("//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js").wait(function(){jQuery.extend(!0,a.SNI,{BOX:{jQuery:a.jQuery}});!1===e?(c("jQuery was defined, executing noConflict"),
a.jQuery.noConflict(!0)):c("jQuery was undefined");c("Loaded jQuery version: "+a.SNI.BOX.jQuery.fn.jquery);c("window.jQuery version is: "+a.jQuery.fn.jquery);c("calling loadApp");v();w.setContextLoaded()}):(jQuery.extend(!0,a.SNI,{BOX:{jQuery:a.jQuery}}),c("Used existing jQuery version: "+a.SNI.BOX.jQuery.fn.jquery),c("window.jQuery version is: "+a.jQuery.fn.jquery),v(),w.setContextLoaded())}(a.SNI.BOX.$LAB)})(window,void 0);
(function(a,d){a.boxContextLoaded(function(d){var c=SNI.BOX.DEBUG.forScope("AUTH"),b={},q=[],f=null;a.SNI=a.SNI||{};a.SNI.BOX=a.SNI.BOX||{};a.SNI.BOX.AUTH=a.SNI.BOX.AUTH||{};a.SNI.BOX.AUTH.EVENTS={LOGIN:"login",LOGOUT:"logout"};a.SNI.BOX.AUTH.registerAuthenticationScheme=function(h,t){if(void 0===h)throw Error("Authentication Scheme registration requires a name!");if(void 0===t)throw Error("Authentication Scheme registration requires a scheme object!");if(void 0!==b[h])throw Error('Authentication Scheme "'+
h+'" is already registered!');if("function"!==typeof t.isAuthenticated)throw Error('Authentication Scheme object property "isAuthenticated" is required!');if("function"!==typeof t.requireLogin)throw Error('Authentication Scheme object property "requireLogin" is required!');if("function"!==typeof t.onLogin)throw Error('Authentication Scheme object property "onLogin" is required!');if("function"!==typeof t.isReady)throw Error('Authentication Scheme object property "isReady" is required!');if("function"===
typeof t.signUrl&&"function"!==typeof t.unSignUrl)throw Error("Authentication Scheme must contain unSignUrl support if signUrl support is provided!");q.push(h);b[h]={};b[h].getName=function(){return h};c("mapping (required) isAuthenticated method for scheme: "+h);b[h].isAuthenticated=t.isAuthenticated.bind(b[h]);c("wrapping (required) requireLogin method for scheme: "+h);b[h].requireLogin=function(a){f=a||null;c("calling (required) requireLogin method for scheme: "+h);t.requireLogin.apply(b[h],arguments);
return b[h]};c("defining new EnvironmentContext for scheme: "+h);var l=new EnvironmentContext("authContextLoaded_"+h);c("assigning win.authContextLoaded_"+h+" callback to onReady for scheme: "+h);b[h].onReady=function(e){a["authContextLoaded_"+h](e.bind(b[h]));return b[h]};var g=[];b[h].beforeLogin=function(a){c("registering beforeLogin handler");g.push(a.bind(b[h]));return b[h]};var p=[];b[h].beforeLogout=function(a){c("registering beforeLogout handler");p.push(a.bind(b[h]));return b[h]};var u=function(a){var e,
l,k=[];c("executing beforeLogin callbacks");for(e=0;e<g.length;e++)l=g[e](a,f),"object"===typeof l&&k.push(l);0<k.length&&c("waiting for "+k.length+" beforeLogin callbacks to finish");d.when.apply(null,k).then(function(){c("triggering login event with parameters:",[a,f]);d(b[h]).trigger(SNI.BOX.AUTH.EVENTS.LOGIN,[a,f])})},v=function(a){var e,g,k=[];c("executing beforeLogout callbacks");for(e=0;e<p.length;e++)g=p[e](a,f),"object"===typeof g&&k.push(g);0<k.length&&c("waiting for "+k.length+" beforeLogout callbacks to finish");
d.when.apply(null,k).then(function(){c("triggering logout event with parameters:",a);d(b[h]).trigger(SNI.BOX.AUTH.EVENTS.LOGOUT,[a])})};b[h].onReady(function(){c("registering (required) onLogin handler for scheme: "+h);t.onLogin(u);c("assigning logout event trigger to onLogout callback for scheme: "+h);if("function"===typeof t.onLogout)t.onLogout(v);else c("logout event not supported by scheme: "+h)});"function"===typeof t.signUrl?(c("mapping (optional) signUrl method for scheme: "+h),b[h].signUrl=
t.signUrl.bind(b[h])):b[h].signUrl=function(a){return a};"function"===typeof t.unSignUrl?(c("mapping (optional) unSignUrl method for scheme: "+h),b[h].unSignUrl=t.unSignUrl):b[h].unSignUrl=function(a){return a};if(!0===t.isReady())c(h+" scheme is ready (before scheme init), setting context loaded without delay"),l.setContextLoaded();else var w=new Date,e=a.setInterval(function(){!0===t.isReady()&&(c(h+" scheme is ready (after scheme init), setting context loaded after delay: "+(+new Date-w)+" ms"),
l.setContextLoaded(),clearInterval(e))},30);return b[h]};a.SNI.BOX.AUTH.getFirstScheme=function(){return 0<q.length?b[q[0]]:null};a.SNI.BOX.AUTH.getSchemeByName=function(a){return a?"object"===typeof b[a]?b[a]:null:null};d(document).on("click",".box-login-hook",function(a){var b=d(this),f=b.data("authScheme"),g=null;f&&(g=SNI.BOX.AUTH.getSchemeByName(f));null===g&&(g=SNI.BOX.AUTH.getFirstScheme());null===g?c("No auth scheme found!  Aborting auth scheme handling!"):(a.preventDefault(),g.requireLogin(b.data("loginOptions")))})})})(window,
void 0);
(function(){var a=0,d=0,n={},c=SNI.BOX.DEBUG.forScope("INIT");window.SNI=window.SNI||{};window.SNI.BOX=window.SNI.BOX||{};window.SNI.BOX.init=function(d){window.boxContextLoaded(function(f){c("SNI.BOX.init()!");if("undefined"===typeof window.BOX_SERVER_HOST)c("Cannot initialize, no window.BOX_SERVER_HOST is defined");else if("undefined"===typeof window.BOX_SERVER_S_API)c("Cannot initialize, no window.BOX_SERVER_S_API is defined");else{var h=f("body");d&&0<f(d).size()&&(h=f(d));var t=h.find("[data-box-id]").not(".box-loading").not(".box-loaded").add(h.filter("[data-box-id]").not(".box-loading").not(".box-loaded"));if(0===
t.size())c("SNI.BOX.init(): No Containers!");else{var l={},g={},p=[];t.each(function(){var e=f(this),d=e.data("boxId");a++;e.attr("id",d+"_"+a);"string"===typeof d&&(e.addClass("box-loading"),p.push(e),"undefined"===typeof l[d]&&(l[d]=[],g[d]=[]),g[d].push(e[0]),e=f(this).data("boxParams"),"object"===typeof e?l[d].push(e):l[d].push({}))});c("SNI.BOX.init(): uniqueContainers",l);var u=b(l);if(0!==u.length){for(var v=[],t=0;t<u.length;t++){var w=u[t];"undefined"===typeof n[w]&&(n[w]={boxId:w,deferred:new f.Deferred},
v.push(w));var e=function(a,e,d){return function(){window.SNI.BOX.initDataHandler(a,e,d)}}(w,h,g[w]);n[w].deferred.done(e)}0!==v.length&&(h=v.map(function(a){return"id\x3d"+a}),h.push("host\x3d"+SNI.BOX.Util.getHost(window.BOX_SERVER_HOST)),h=h.join("\x26"),function(a){f.ajax({url:a,dataType:"jsonp",jsonp:"_callback",cache:!0,jsonpCallback:"window_SNI_BOX_initCallback",error:function(a,e,d){for(a=0;a<v.length;a++)n[u[a]].deferred.reject(),c("Failed to aquire syndication information for box-id ["+
u[a]+"]");c("Error [textStatus\x3d"+e+"] [errorThrown\x3d"+d+"]")}})}(window.BOX_SERVER_S_API+"?"+h))}}}})};var b=function(a){var d=[],b;for(b in a)a.hasOwnProperty(b)&&d.push(b);return d};window_SNI_BOX_initCallback=function(a,d,b){c("window_SNI_BOX_initCallback: Got data:",JSON.stringify(a));window.boxContextLoaded(function(d){var b,c;if("object"!==typeof a)throw Error("invalid response data");for(b=0;b<a.containerIds.length;b++)c=a.containerIds[b],n[c].data=a[c],n[c].boxHost=a.boxHost,n[c].boxApiUrlPrefix=
a.boxApiUrlPrefix,n[c].deferred.resolve();for(b=0;b<a.alsoLoadedModuleIds.length;b++)c=a.alsoLoadedModuleIds[b],"undefined"===typeof n[c]&&(n[c]={boxId:c,deferred:new d.Deferred}),n[c].data=a[c],n[c].boxHost=a.boxHost,n[c].boxApiUrlPrefix=a.boxApiUrlPrefix,n[c].deferred.resolve()})};window.SNI.BOX.initDataHandler=function(a,b,h){c("Handling data for box-id ["+a+"] -\x3e ",n[a].data);window.boxContextLoaded(function(b){var f=n[a].data,g=n[a].boxHost,p=n[a].boxApiUrlPrefix,u=b(h),v=new EnvironmentContext("moduleContext_"+
a+"_"+d),w=[];d+=1;c("Containers ("+u.size()+")");u.each(function(){var a=b(this);c("Handling container: ",a);if(a.hasClass("box-loaded"))c("Module container already loaded: ",a);else{var d=a.data("boxParams");void 0===d&&(d={});for(var h=a.data("boxPreload"),n=a.attr("id"),k=0;k<f.modules.length;k++){var q=f.modules[k],u=b("\x3cdiv /\x3e",{id:n+"_"+k}),z=!0===q.isPublic;a.append(u);var B=q.params.url,I;for(I in d)d.hasOwnProperty(I)&&"object"!==typeof d[I]&&(B=SNI.BOX.Util.appendParam(B,I,d[I]));
!0===z&&(B=SNI.BOX.Util.appendParam(B,"host",SNI.BOX.Util.getHost(g)));!0!==z&&SNI.BOX.Util.isCrossDomain(B)&&(z=SNI.BOX.AUTH.getSchemeByName(d.authSchemeName),null!==z&&(B=z.signUrl(B)));var z=b.extend(!0,{boxHost:g,boxApiUrlPrefix:p},q.params,d,{url:B,synchronizedContext:v}),B=SNI.BOX.Util.getUrlPrefix(window.BOX_SERVER_S_API),y=new b.Deferred;w.push(y);u=function(d,f,g,h,k,m){return function(){c("SNI.BOX.autoRun params: ",d,f,g,h,k,m);k||(b(d).parent().one("box.sync_"+d.id,function(){c("Heard box.sync, resolving $syncDfd for module",
d);m.resolve()}),SNI.BOX.autoRun(d,f,g,h),a.trigger("box.load",[d,f,g,h,k]));a.addClass("box-loaded").removeClass("box-loading")}}(u[0],q.moduleName,q.moduleClass,z,h,y);SNI.BOX.Util.loadStyles(B,q.params.styleDependencies);SNI.BOX.Util.loadScripts(B,q.params.scriptDependencies).then(u)}}});b.when.apply(null,w).then(function(){c("all modules have been synchronized!");v.setContextLoaded()})})};SNI.BOX.loadModule=function(a,d,b){try{(function(a,d){window.boxContextLoaded(function(c){var f=c("\x3cdiv /\x3e",
{"data-box-id":a,"data-box-params":"object"===typeof d?JSON.stringify(d):d,"data-box-preload":b});c("body").append(f)})})(a,d),SNI.BOX.init()}catch(t){c("Caught error while in SNI.BOX.loadModule: ",t)}};window.boxContextLoaded(function(a){a(document).on("click","[data-box-target-id]",function(d){d.preventDefault();d=a(this);c("Heard click event for [data-box-target-id]: "+d.data("boxTargetId")+", params: ",d.attr("data-box-params"));SNI.BOX.loadModule(d.data("boxTargetId"),d.attr("data-box-params"))})})})();
window.boxContextLoaded(function(a){(function(a){var n=0;a.plugin=function(c,b){var q="plugin"+n;n+=1;b||(b=c);return function(f){var h=arguments;if(!f||"object"===typeof f){var t=a(this).filter(function(){return!a(this).data(q)});if(0<t.length){var l=a.extend(!0,{},c,f);t.each(function(){var c=a(this),f=function(b,e){a.each(b.split(/\s+/),function(a,d){c.bind(q+"_"+d,e)})},g={data:function(a,d){var b=c.data(q+"_data");b||(b={},c.data(q+"_data",b));if("undefined"===typeof d)return b[a];b[a]=d},bind:f,
pluginName:q,plugin:function(){return g},trigger:function(b,e){c.trigger(a.extend(a.Event(q+"_"+b),e),[g])}};c.data(q,g);void 0!==l.events&&a.each(l.events,f);g.isInitializing=!0;b.apply(this,[g,l]);g.trigger("initialized");g.isInitializing=!1})}}var g;this.each(function(){var b=a(this).data(q);b&&(b=b[f])&&("function"===typeof b&&(b=b.apply(null,Array.prototype.slice.call(h,1))),g||(g=b))});return"undefined"!==typeof g?g:this}}})(a)});
window.boxContextLoaded(function(a){(function(a,n,c){var b=a(n),q=n.document;a.plugin2=function(b,c){var t="plugin-"+b,l=b+"-options";c._mergeOptions=function(b){return a.extend(!0,{},this._defaultOptions,b)};c.closestInit=function(){var b=this.$caller.closest("."+t);return 0<b.length?b:a(q)};c.option=function(b,c){var f=this.closestInit();if("undefined"===typeof b)return(f=f[0])?a.data(f,l):null;if("undefined"===typeof c)return(f=f[0])?a.data(f,l)[b]:null;f.each(function(){a.data(this,l)[b]=c});
return this.$caller};c.live=function(b,c){var f=this,h=f.$caller;c=f._mergeOptions(c);f._init&&f._init(b,c);h.onCreate(b,function(){var b,e;a.data(this,l)||(b=a(this),e=a.extend({},f,{$caller:b}),a.data(this,l,c),b.addClass(t),e._create&&e._create(this,c))});f._createAll&&h.bind("create",function(a){f._createAll(a.target,b,c)});return h};c.init=function(a){return this.live(null,a)};a.fn[b]=function(g){var l=a.extend({},c,{$caller:this});if(!g||"object"===typeof g)return l.init(g);g=""+g;return"_"!==
g.substr(0,1)&&l[g]?l[g].apply(l,Array.prototype.slice.call(arguments,1)):a.error("["+g+"] method doesn't exist on ["+b+"] plugin!")}};a.run=function(a){a();return a};a.throttle=function(a,b){var c=0,d,g;return 0>=a?b:function(){var p,n,q;g=arguments;d||(p=this,n=+new Date,q=a-n+c,0>=q?(c=n,b.apply(p,g)):d=setTimeout(function(){c=n;d=null;b.apply(p,g)},q))}};(function(){var c,h,n,l,g,p,u,v,w,e,r;c=a("\x3cdiv/\x3e",{css:{height:"100%",left:0,position:"fixed",top:0,"user-select":"none",width:"100%",
"z-index":1E6}});h=function(b){g&&(clearTimeout(g),g=null);e=null;a(q.body).css("user-select","");n&&(n.unbind(".drag"),n=null);r&&(r(b),r=null)};a.drag=function(b,x,k,M,E){var z;1!==x.which||x.altKey||x.ctrlKey||x.metaKey||x.shiftKey||(z={$dragCover:c},h(x),a(q.body).css("user-select","none"),n=a(b),n.bind("dragstart.drag",function(){return!1}),p=v=x.pageX,u=w=x.pageY,l=function(){var h=function(){e=function(a){return M.call(b,a,z)};r=function(a){return E.call(b,a,z)};a(q.body).append(c);k.call(b,
x,z)};x.dragImmediately?h():g=setTimeout(function(){var a=v-p,b=w-u;Math.sqrt(a*a+b*b)<(x.dragDistance||5)?l():h()},x.dragDelay||100)},l())};b.mousemove(a.throttle(50,function(a){g&&(v=a.pageX,w=a.pageY);e&&e(a)}));b.mouseup(function(a){h(a);c.remove()})})();a.fn.isFixedPosition=function(){for(var a=this,b;;){if("fixed"===a.css("position"))return!0;b=a.offsetParent();if(0===a.length||a[0]===b[0])break;else a=b}return!1};a.fn.zIndex=function(){for(var a,b=this;0<b.length;b=b.parent()){try{a=parseInt(b.css("z-index"),
10)}catch(c){break}if(!isNaN(a)&&0!==a)break}return a};(function(){var b=a.fn.delegate;a.fn.delegate=function(){return arguments[0]?b.apply(this,arguments):a.fn.bind.apply(this,Array.prototype.slice.call(arguments,1))}})();(function(){"oninput"in q.createElement("input")||(a.event.special.input={add:function(b){var c=a(this);b=b.selector;var n,l;n=a.throttle(50,function(){a(this).trigger("input")});c.delegate(b,"keyup",function(){setTimeout(n,0)});l=function(){var b=a.data(this,"input-checkInterval");
b&&(clearInterval(b),a.removeData(this,"input-checkInterval"))};c.delegate(b,"focus",function(){l.call(this);a.data(this,"input-checkInterval",setInterval(n,50))});c.delegate(b,"blur",l)}})})();a.elementFromPoint=function(b,c){var n=q.elementFromPoint(b,c);return n&&(3===n.nodeType&&(n=n.parentNode),n)?a(n):a()};a.fn.onCreate=function(b,c){b?this.bind("create",function(n){a(n.target).find(b).each(c)}):this.each(c)};a.easing.easeOutBack=function(a,b,c,d,g,p){void 0===p&&(p=1.70158);return d*((b=b/
g-1)*b*((p+1)*b+p)+1)+c}})(a,window)});
window.boxContextLoaded(function(a){(function(a,n,c){var b=a(n),q=n.document;a.plugin2("popup",{_defaultOptions:{padding:{left:35,right:35,top:20}},_create:function(c){c=a(c);this.option();var h=a("\x3cdiv/\x3e",{"class":"popup"}),n=a("\x3cdiv/\x3e",{"class":"content"}),l=a("\x3cdiv/\x3e",{"class":"closeButton"}),g=c.attr("name");g&&h.attr("name",g);h.bind("open.popup",function(){var c=a(this),f=c.data("popup-scrollLeft"),g=c.data("popup-scrollTop");"number"!==typeof f&&"number"!==typeof g&&(c.data("popup-scrollLeft",
b.scrollLeft()),c.data("popup-scrollTop",b.scrollTop()));c.show()});h.bind("restoreOriginalPosition.popup",function(){var c=a(this),f=c.data("popup-scrollLeft"),g=c.data("popup-scrollTop");c.removeData("popup-scrollLeft");c.removeData("popup-scrollTop");"number"===typeof f&&"number"===typeof g&&(b.scrollLeft(f),b.scrollTop(g))});h.bind("close.popup",function(){var b=a(this);b.hide();a(".popup").each(function(){var c=a(this),f=c.popup("source");f&&a.contains(b[0],f[0])&&c.popup("close")})});l.bind("click.popup",
function(){a(this).popup("close")});g=a(q.body);n.append(c);n.append(l);h.append(n);g.append(h)},open:function(){this.$caller.popup("container").trigger("open");return this.$caller},restoreOriginalPosition:function(){this.$caller.popup("container").trigger("restoreOriginalPosition");return this.$caller},close:function(){this.container().trigger("close");return this.$caller},container:function(){return this.$caller.closest(".popup")},content:function(){return this.$caller.popup("container").find("\x3e .content")},
source:function(b,h){var n=this.option();h&&(30>b.height()||"number"!==typeof h.pageX||"number"!==typeof h.pageY)&&(h=c);var l,g,p;if(l=this.$caller.popup("container"))g=l.popup("content"),p=g.find("\x3e .marker"),0===p.length&&(p=a("\x3cdiv/\x3e",{"class":"marker"}),g.append(p));if("undefined"===typeof b||null===b)return l[0]?a.data(l[0],"popup-$source"):null;l.each(function(){a.data(this,"popup-$source",b)});var u=b.offset(),v=l.outerWidth(),w=0;g=h?h.pageX-v/2:u.left+(b.outerWidth()-v)/2;if(g<
n.padding.left)w=g-n.padding.left,g=n.padding.left;else{var e=g+v-a(q).width()+n.padding.right;0<e&&(w=e,g-=e)}v=(v-p.outerWidth())/2+w;p.css("left",5>v?5:v);p=h?h.pageY:u.top+b.outerHeight();30>p&&(p=30);if(u=b.isFixedPosition())g-=a(window).scrollLeft(),p-=a(window).scrollTop();v=b.closest(".popup");0===v.length&&(v=b.parent());n=null===n.zIndex?b.parent().zIndex()+1:n.zIndex;l.css({left:g,margin:0,position:u?"fixed":"absolute",top:p,"z-index":n});return this.$caller}});b.click(function(b){var c=
b.target;0===a(c).popup("container").length&&a(".popup").each(function(){var b=a(this),f=b.popup("source");f&&0<f.length&&(f=f[0],f==c||a.contains(f,c)||b.popup("close"))})});b.keydown(function(b){if(27===b.which)return b=a(".popup"),0<b.length?(b.popup("close"),!1):!0})})(a,window)});
window.boxContextLoaded(function(a){var d=SNI.BOX.DEBUG.forScope("EXECUTION","FRAME");a.fn.frame=a.plugin({refresh:{hrefAttribute:"data-refresh-href",triggerAttribute:"data-refresh-trigger",intervalAttribute:"data-refresh-interval",requestType:"data-request-type",extraData:"extra-data"},hrefAttribute:"data-frame-href",preventConcurrentClass:"dari-frame-prevent-concurrent",frameClass:"dari-frame",beforeLoadEventAttribute:"data-before-load-event",loadingClass:"dari-frame-loading",loadedClass:"dari-frame-loaded",
errorClass:"dari-frame-error",ignoreClass:"dari-frame-ignore",preventConcurrent:!1,debug:!1,setBody:function(d){a(this).html(d)}},function(n,c){var b=a(this),q=0,f=function(a){-1===window.location.hash.indexOf("_debugFrame")&&!0!==c.debug||"undefined"===typeof console||console.log(a)},h=function(b,d,g){var h=b.attr("name");h||(q+=1,h="frameTarget"+q+ +new Date);!0!==g&&a("."+c.frameClass+"["+c.refresh.triggerAttribute+'~\x3d"'+h+'"]').each(function(){var b=a(this),e=b.attr("name");f('frame "'+h+'" calling loadPage for frame "'+
("undefined"===typeof e?b.attr(c.refresh.hrefAttribute):b.attr("name"))+'"');void 0!==d?-1===d.indexOf(b.attr("name"))&&setTimeout(function(){u(b,b.data("source"),"get",b.attr(c.refresh.hrefAttribute),null,null,d+" "+h,!0)},0):setTimeout(function(){u(b,b.data("source"),"get",b.attr(c.refresh.hrefAttribute),null,null,h,!0)},0)})},t=function(a,b,c){var d="";"html"===c&&(void 0!==a&&null!==a&&(d+="_format\x3d"+a),void 0!==b&&null!==b&&(0<d.length&&(d+="\x26"),d+="_result\x3d"+b));return d},l=function(e,
d,f,g){var k=a(e);e=null;"_top"!==d&&"_self"!==d&&"_blank"!==d&&"_new"!==d&&(d&&"_parent"===d?void 0!==a.fn.popup&&0<k.closest("."+c.frameClass).popup("container").size()?(d=k.closest("."+c.frameClass),k=d.data("rootSource"),void 0!==k&&(d.removeData("rootSource"),e=k.closest("."+c.frameClass),0<e.size()?(e.popup("close"),h(e,f,g)):(d.popup("close"),h(d,f,g)))):e=k.closest("."+c.frameClass).parent().closest("."+c.frameClass):d?(e=a("."+c.frameClass+'[name\x3d"'+d+'"]'),0===e.size()&&(e=a("."+c.frameClass+
'[name\x3d"'+d+'"]')),0===e.size()&&void 0!==a.fn.popup&&(e=a('\x3cdiv class\x3d"'+c.frameClass+'" name\x3d"'+d+'"\x3e \x3c/div\x3e'),b.append(e),e.popup("init"),e.popup("source",k))):e=k.closest("."+c.frameClass));return null===e||0===e.size()?null:e},g=function(b,d,g,h){var k=(b.data("loadVersion")||0)+1;b.data("loadVersion",k);b.data("startTime",new Date);b.data("source",d);b.data("rootSource")||b.data("rootSource",d);b.addClass(c.loadingClass);"undefined"!==typeof d&&null!==d&&d.addClass(c.loadingClass);
if(void 0!==a.fn.popup){var l=b.popup("container");if(0<l.size()){l.addClass(c.loadingClass);var p=b.popup("source");!l[0]||"undefined"===typeof d||a.contains(l[0],d[0])||p&&p[0]==d[0]||(b.popup("source",d,g),b.empty());!0!==h&&b.popup("open")}}!0===!!b.attr(c.beforeLoadEventAttribute)&&b.trigger("frame.beforeLoad",d);f("--EVENT-- [beginLoad]");n.trigger("beginLoad",{version:k,$frame:b,$source:d});b.trigger("beginLoad",{version:k,$frame:b,$source:d});return k},p=function(b,g,m,p,k,q,t,v,u){var w=
new Date;if(g>=b.data("loadVersion")){var y;if(q){if("_top"===q||"_self"===q){void 0!==a.fn.popup&&b.popup("close");t=t||window.location.href;setTimeout(function(){window.location.href=t},0);return}y=l(b.data("source"),q,v,u);null===y||y.is(b)||("_parent"!==q&&(y.data("rootSource")||(b.data("rootSource")?y.data("rootSource",b.data("rootSource")):b.data("source")&&y.data("rootSource",b.data("source")))),b.data("source")&&y.data("source",b.data("source")),b.removeClass(c.loadingClass).addClass(c.loadedClass),
b.removeClass(c.errorClass),void 0!==a.fn.popup&&(b.popup("container").removeClass(c.loadingClass).addClass(c.loadedClass),b.popup("close")),b=y)}var C=b.data("source");if("undefined"===typeof q||null!==y)b.removeClass(c.loadingClass).addClass(c.loadedClass),void 0!==a.fn.popup&&(q=b.popup("container"),q.removeClass(c.loadingClass).addClass(c.loadedClass),"undefined"!==typeof C&&null!==C&&(C.removeClass(c.loadingClass),C.removeClass(c.errorClass)),y=b.popup("source"),!q[0]||"undefined"===typeof C||
a.contains(q[0],C[0])||y&&y[0]==C[0]||(b.popup("source",C),b.empty()),!0!==u&&b.popup("open")),"object"===typeof m&&"jsonp"===p&&"html"===k&&(m=m.result),"string"===typeof m&&(m=m.replace(/^(?:.|[\r\n])*?<body[^>]*>/ig,""),m=m.replace(/<\/body>(?:.|[\r\n])*?$/ig,"")),c.setBody.call(b[0],m),b.change(),a(window).resize();h(b,v,u);f("--EVENT-- [endLoad]");m=new Date;n.trigger("endLoad",{version:g,$frame:b,$source:C});d("triggering endLoad (plugin) took: "+(new Date-m)+" ms");m=new Date;b.trigger("endLoad",
{version:g,$frame:b,$source:C});d("triggering endLoad ($frame) took: "+(new Date-m)+" ms")}d("endLoad took: "+(new Date-w)+" ms")},u=function(b,d,h,l,k,n,q,v){var u=g(b,d,n,v),w=b.data("extraFormData"),y=b.data("ajaxDataType"),C=b.data("ajaxResultType"),D=b.data("sourceDataFormat");n=b.data("jsonpCallbackParam");var F=b.data("jsonpCallback"),C=t(y,C,D);0<C.length&&("undefined"===typeof w&&(w=""),0<w.length&&(w+="\x26"),w+=C);"undefined"!==typeof w&&0<w.length&&(l+=(0>l.indexOf("?")?"?":"\x26")+w);
h={cache:!1,type:h,url:l,data:k,success:function(a,c,d){c=d.getResponseHeader("X-Frame-Target");var g=d.getResponseHeader("X-Frame-Redirect");a="json"===y||"jsonp"===y?a:d.responseText;d=+new Date-b.data("startTime");"undefined"!==typeof d&&f("frame.js took "+d+" ms loading url: "+l);p(b,u,a,y,D,c,g,q,v)},error:function(){"undefined"!==typeof d&&null!==d&&d.addClass(c.errorClass);b.addClass(c.errorClass)}};if("json"===y||"jsonp"===y)h.dataType=y,h.jsonp=n?n:"_callback",F&&(h.jsonpCallback=F);f(h);
a.ajax(h);return u};b.bind("reloadFrame",function(b,d,f){var g=b.target;b=null;"undefined"!==typeof d&&d.is("."+c.frameClass)?b=d:"undefined"!==typeof g&&a(g).is("."+c.frameClass)&&(b=a(g));null!==b&&(d=b.attr(c.refresh.hrefAttribute),"undefined"!==typeof d&&u(b,f,"get",d,null,null,null,!0))});b.on("click",'a[href]:not([href^\x3d"java"])',function(b){var d=a(this),g=d.attr(c.hrefAttribute);"undefined"===typeof g&&(g=d.attr("href"));if(d.is("."+c.ignoreClass)||"undefined"===typeof g||""===g||"#"===
g||0<d.closest("."+c.ignoreClass).size())return!0;var h=l(d,d.attr("target"));if(null==h||0===h.size())return!0;if(h.is("."+c.loadingClass)&&(!0===c.preventConcurrent||0<d.closest("."+c.preventConcurrentClass).size()))return!1;if(null!==h&&0<h.size()){var k=d.attr(c.refresh.requestType);if(null!=k&&"POST"===k.toUpperCase()){var n=d.data(c.refresh.extraData);null!=h.data("ajaxDataType")&&"JSONP"===h.data("ajaxDataType").toUpperCase()&&h.data("ajaxDataType","JSON");f("[frame.js] passing extraData:"+
c.refresh.extraData+":"+n)}else k="GET",n=null;u(h,d,k,g,n,b);b.preventDefault();b.stopPropagation()}else return!0});var v=function(b){b=a(b.target);0<b.size()&&b.data("frameValidated",!0)};b.on("submit","form",function(d,h){var m=a(this),n=m.data("storedTarget"),k=n||l(m,m.attr("target"));if(null===k||0===k.size()||m.is("."+c.ignoreClass))return!0;if(k.is("."+c.loadingClass)&&(!0===c.preventConcurrent||0<m.closest("."+c.preventConcurrentClass).size()))return!1;if(!0===m.data("frameValidate")){m.removeData("frameValidated");
b.on("frame.validate",v);var t=!1;try{m.trigger("frame.validate")}catch(w){f("[frame.js]: caught exception while performing validation: "),f(w),t=!0}b.off("frame.validate",v);if(!0!==m.data("frameValidated")&&!1===t)return!1}t="undefined"===typeof h?m.find("input[type\x3dsubmit],input[type\x3dimage],button[type\x3dsubmit]").filter(":visible").first():a(h);0===t.size()&&(t=m);var z=m.attr("action");if("multipart/form-data"!==m.attr("enctype"))return u(k,t,m.attr("method"),z,m.serialize(),d),!1;var B=
k.attr("data-extra-form-data"),I=k.data("ajaxDataType"),y=k.data("ajaxResultType"),C=k.data("sourceDataFormat");"html"===C&&("json"===I||"jsonp"===I&&"html"!==y)&&("undefined"===typeof B&&(B=""),0<B.length&&(B+="\x26"),B+="_format\x3djson");m.attr("action",z+(0>z.indexOf("?")?"?":"\x26")+B);z=m.find(':hidden[name\x3d"_isFrame"]');0===z.length&&(z=a('\x3cinput name\x3d"_isFrame" type\x3d"hidden" value\x3d"true"/\x3e'),m.prepend(z));n||m.data("storedTarget",k);var D=m.attr("target");D||(q+=1,D="frameTarget"+
q+ +new Date,m.attr("target",D));m=a('iframe[name\x3d"'+D+'"]');0!==m.length&&(f('found iframe with name\x3d"'+D+'", removing "name" attribute.'),m.removeAttr("name"));m=a('\x3ciframe name\x3d"'+D+'"\x3e\x3c/iframe\x3e');m.hide();b.is("body")?b.append(m):b.after(m);f('created iframe with name\x3d"'+D+'"');var F=g(k,t,d,!1);m.bind("load."+c.frameClass,function(){var b=a('iframe[name\x3d"'+D+'"]');f('load handler for iframe with name\x3d"'+b.attr("name")+'"');var d=b.contents().find("body"),e=d.attr("data-x-frame-target"),
g=d.attr("data-x-frame-redirect"),h=+new Date-k.data("startTime");"undefined"!==typeof h&&f("frame.js took "+h+" ms loading url: "+url);p(k,F,d.text(),null,C,e,g);b.unbind("."+c.frameClass);setTimeout(function(){f('removing iframe with name\x3d"'+b.attr("name")+'"from DOM');b.remove()},0);f('exiting load handler for iframe with name\x3d"'+b.attr("name")+'"')});d.stopPropagation();return!0});var w=function(d){var g=d.attr(c.refresh.hrefAttribute);if("undefined"!==typeof g){var h=u(d,null,"get",g,null,
null,null,!0);b.bind("endLoad",function(b){if(b.$frame.is(d)&&h===b.version){var g=parseInt(d.attr(c.refresh.intervalAttribute),10);f("--EVENT-- [refresh]: next in "+g+"s");0<g&&setTimeout(function(){w(d)},1E3*g)}a(this).unbind(b)})}};a(function(){a("."+c.frameClass+"["+c.refresh.intervalAttribute+"]").each(function(){var b=a(this),d=parseInt(b.attr(c.refresh.intervalAttribute),10);0<d&&setTimeout(function(){w(b)},1E3*d)})})})});
window.boxContextLoaded(function(a){a.fn.fontChecker=function(d){function n(){f===q.offsetWidth?0>d.timeOut?(c.removeClass(d.loadingClass),c.addClass(d.failClass),d.fail.call(c[0],[d])):(c.addClass(d.loadingClass),setTimeout(n,d.delay),d.timeOut-=d.delay):(c.removeClass(d.loadingClass),c.addClass(d.completeClass),d.load.call(c[0],[d]))}var c=a(this),b={font:c.css("font-family"),fontAwesome:!1,loadingClass:"",failClass:"",completeClass:"",load:function(){},fail:function(){},isIconographyFont:!1,iconographyTestClass:"icon-glass",
testFont:"Comic Sans MS",testString:"QW@HhsXJ",delay:30,timeOut:5E3};d=a.extend(b,d);var q=document.createElement("span");q.style.position="absolute";q.style.top="-9999px";q.style.left="-9999px";q.style.visibility="hidden";q.style.fontFamily=d.testFont;q.style.fontSize="250px";!0===d.isIconographyFont?q.className=d.iconographyTestClass:q.innerHTML=d.testString;document.body.appendChild(q);var f=q.offsetWidth;q.style.fontFamily=d.font+","+d.testFont;n()}});SNI.BOX.DEBUG.enable("CLICK_TRACKING");SNI.BOX.DEBUG.enable("INIT");
(function(a,d){a.SNI=a.SNI||{};a.boxContextLoaded(function(n){var c=a.SNI.BOX.DEBUG.forScope("UTIL");n.extend(!0,a.SNI,{BOX:{Config:{SocialUploader:{pickOptions:{multiple:!1}}}},SocialUploader:{jQuery:n}});(function(){var b=null;n.extend(!0,a.SNI.BOX,{uploader:function(a){b=arguments}});a.BOX_SIMPLE_UPLOADER_URL===d?a.SNI.BOX.DEBUG("Cannot instantiate Simple Uploader without window.BOX_SIMPLE_UPLOADER_URL"):a.SNI.BOX.$LAB.script(a.BOX_SIMPLE_UPLOADER_URL).wait(function(){a.socialUploaderContextLoaded(function(){n.extend(!0,
a.SNI.BOX,{uploader:function(b,f,h,t){var l=new n.Deferred;b=n(b);var g=SNI.BOX.Config.SocialUploader.pickOptions||{},p=SNI.BOX.Config.SocialUploader.storeOptions||{},u={};0<b.size()&&(b.data("suPickOptions")!==d&&n.extend(!0,g,b.data("suPickOptions")),b.data("suStoreOptions")!==d&&n.extend(!0,p,b.data("suStoreOptions")),b.data("suAssetMetaData")!==d&&n.extend(!0,u,b.data("suAssetMetaData")));"object"===typeof f&&n.extend(!0,g,f);"object"===typeof h&&n.extend(!0,p,h);"object"===typeof t&&n.extend(!0,
u,t);c("Triggering box.beforeUpload: ",u,g,p);n(a.SNI.BOX).trigger("box.beforeUpload",[u,g,p]);CP_SERVICE_FILE_UPLOAD.uploadFile(function(a){l.resolve(a,g,p,u)},function(){SNI.BOX.DEBUG("Social Upload ERROR callback triggered!");l.fail()},u,g,p);return l}});null!==b&&a.SNI.BOX.uploader.apply(null,b)})})})();n.extend(!0,a.SNI,{BOX:{Util:{trackOmniture:function(b){a.SNI.BOX.DEBUG("trackOmniture called with data: ",b);if(b===d||null===b||""===b)b={};if("object"!==typeof b)throw Error("Illegal argument.");
var c=a.mdManager.getParameterString("UniqueId"),f=c.split("-");if(3>f)throw Error('"'+c+'" is not a valid UniqueId.');b.assetId!==d&&(f[3]=b.assetId);b.contentType!==d&&(f[2]=b.contentType);b.mainAssetId!==d&&(f[1]=b.mainAssetId);a.mdManager.setParameter("UniqueId",f.join("-"));b.assetUrl!==d&&(a.mdManager.setParameter("oUrl",a.mdManager.getParameterString("Url")),a.mdManager.setParameter("Url",b.assetUrl));if("object"!==typeof s||"function"!==typeof s.t)throw Error("Omniture tracking object ('s') is not defined");
s.t();a.mdManager.setParameter("UniqueId",c)},alert:function(b){b=n.extend({},{message_html:"Unspecified message",message_type:"success",message_target:"mrb-primary-feedback",action_type:"",action_text:"",action_url:"",action_target:"",action_button_class:"",action_click_function:"",data_action:"",icon_class:"mrb-success-icon",notification_display_class:"mrb-notification-display"},b);!0===SNI.BOX.Util.isMobile()&&(SNI.BOX.DEBUG("Use mobile notifications"),b.message_target="mrb-mobile-notification");
var d="";""!=b.action_type&&(""!==b.action_url?d="\x3ca href\x3d'"+b.action_url+"' target\x3d'"+b.action_target+"' class\x3d'action "+b.action_type+"'\x3e"+b.action_text+"\x3c/a\x3e":""!==b.action_click_function?d="\x3ca href\x3d'javascript:;' target\x3d'"+b.action_target+"' onclick\x3d'"+b.action_click_function+"' class\x3d'action "+b.action_type+"'\x3e"+b.action_text+"\x3c/a\x3e":SNI.BOX.DEBUG("An action was added to an alert without an URL or Function"));""!=b.data_action&&(d="\x3ca class\x3d'action undo recover-folder-item'\x3e"+
b.action_text+"\x3c/a\x3e");if("mrb-primary-feedback"===b.message_target){var c=n("#mrb-primary-feedback");1>c.length?n(".mrb-page-alert-container").append("\x3cdiv id\x3d'mrb-primary-feedback' class\x3d'"+b.message_type+"'\x3e\x3cspan class\x3d'box-ss-check'\x3e\x3c/span\x3e\x3cspan class\x3d'message'\x3e"+b.message_html+"\x3c/span\x3e"+d+"\x3c/div\x3e").show():c.removeClass().addClass(b.message_type).html("\x3cspan class\x3d'box-ss-check'\x3e\x3c/span\x3e\x3cspan class\x3d'message'\x3e"+b.message_html+
"\x3c/span\x3e"+d).show()}else if("mrb-mobile-notification"===b.message_target){if(c=n("."+b.message_target),a.SNI.BOX.DEBUG("triggering mobile notification..."),1<=c.length){a.SNI.BOX.DEBUG("found notification container, building notification html....");var h=b.notification_display_class;c.removeClass(h);c.removeClass("mrb-loading-display");c.empty();var t=n("\x3cdiv /\x3e",{class:"mrb-mobile-notification-top"}),l=n("\x3ci /\x3e",{class:b.icon_class});b=n("\x3cspan /\x3e").html(b.message_html);c.append(t);
c.append(d);t.append(l).append(b);c.addClass(h)}}else a.SNI.BOX.DEBUG("alert",b),n(b.message_target).empty().append("\x3cdiv class\x3d'"+b.message_type+"'\x3e\x3cspan class\x3d'box-ss-check'\x3e\x3c/span\x3e\x3cspan class\x3d'message'\x3e"+b.message_html+"\x3c/span\x3e"+d+"\x3c/div\x3e").show();n(document).on("click scroll",function(b){a.SNI.BOX.Util.close_alert("#mrb-primary-feedback")})},test_alert:function(){a.SNI.BOX.Util.alert({message_html:"Unspecified message Unspecified message Unspecified message Unspecified message",
message_type:"success",message_target:"mrb-primary-feedback",action_type:"undo",action_text:"undo",action_url:"#test-alert-action-url",action_target:"",action_click_function:"",data_action:""})},createCookie:function(b){a.location&&n.cookie("mrb-message-alert",JSON.stringify(b),{expires:1,path:"/",domain:a.SNI.BOX.Util.getDomain(a.location)})},destroyCookie:function(){a.location&&n.removeCookie("mrb-message-alert",{path:"/",domain:a.SNI.BOX.Util.getDomain(a.location)});n.removeCookie("mrb-message-alert")},
displayCookieMessage:function(){var b=n.cookie("mrb-message-alert");"string"===typeof b&&0<b.length&&(b=JSON.parse(n.cookie("mrb-message-alert")))&&(a.SNI.BOX.Util.alert(b),a.SNI.BOX.Util.destroyCookie(b))},close_alert:function(a){n(a).hide()},frameValidate:function(a,c){var d=!0;a.find('[data-required\x3d"true"]').each(function(){var a=n(this);a.val()||(a.parent().addClass("has-error"),d=!1)});d||(c.stopPropagation(),c.stopImmediatePropagation(),c.preventDefault())},isLocalStorageSupported:function(){if(void 0===
typeof a.localStorage)return!1;try{return a.localStorage.setItem("boxTest","boxTest"),a.localStorage.removeItem("boxTest"),!0}catch(b){return!1}},checkUserAgent:function(a){return!0===RegExp(a).test(navigator.userAgent)},isIpad:function(){return a.SNI.BOX.Util.checkUserAgent("iPad")},isIphone:function(){return a.SNI.BOX.Util.checkUserAgent("iPhone")},isIOSMobile:function(){return a.SNI.BOX.Util.isIphone()},isIOS:function(){return a.SNI.BOX.Util.isIOSMobile()||a.SNI.BOX.Util.isIpad()},isAndroid:function(){return a.SNI.BOX.Util.checkUserAgent("Android")},
isAndroidPhone:function(){return a.SNI.BOX.Util.isAndroid()&&-1!==navigator.userAgent.toLowerCase().indexOf("mobile")},isAndroidTablet:function(){return a.SNI.BOX.Util.isTouch()&&a.SNI.BOX.Util.isAndroid()&&!0===!/Mobile/i.test(navigator.userAgent)},isMsieMobile:function(){return a.SNI.BOX.Util.checkUserAgent("IEMobile/")},isMobile:function(){return a.SNI.BOX.Util.isIOSMobile()||a.SNI.BOX.Util.isAndroidPhone()||a.SNI.BOX.Util.isMsieMobile()},isTouch:function(){return"ontouchstart"in a||"onmsgesturechange"in
a||!!navigator.msMaxTouchPoints},isTablet:function(){return!0===a.SNI.BOX.Util.isTouch()&&(a.SNI.BOX.Util.isAndroid()||a.SNI.BOX.Util.isIOS())&&!a.SNI.BOX.Util.isMobile()},isPortraitOrientation:function(){return a.outerWidth<a.outerHeight},isLandscapeOrientation:function(){return a.outerWidth>a.outerHeight}}}})})})(window,void 0);
window.boxContextLoaded(function(a){var d=SNI.BOX.DEBUG.forScope("FN_STARTUP"),n=SNI.BOX.DEBUG.forScope("CLICK_TRACKING");a(function(){var c=a('article[itemtype\x3d"http://schema.org/Recipe"]'),c=SNI.BOX.Util.schemaToJson(c,!0);a(SNI.BOX.Util.getByPath(c,"0/_DOMrefs/image/0"));var b=function(b,c){var f;a:{f=a(this);var h=f.closest("section"),q,t,e;if(0<h.size())if(q=h.children(".clicktracking").first(),0<q.size())if(t=q.data("componentPath"))if(e=t.split("/"),0<e.length){f=e[e.length-1];break a}else n('No valid segments in [data-component-path] on class\x3d"clicktracking" element!',
t,q,h,f);else n('No [data-component-path] defined on class\x3d"clicktracking" element!',q,h,f);else n('No class\x3d"clicktracking" child element of \x3csection\x3e!',h,f);else n("No parent \x3csection\x3e defined for element!",f);f=null}d("Analytics moduleName:",f);null!==f&&SNI.Analytics.moduleTrackLS(b.target,{ModuleName:f,LinkTitle:"Save Recipe",LinkPosition:1,TargetUrl:"Save Recipe: "+c.asset.id})};try{void 0!==window.mdManager&&void 0!==window.mdManager.getPageType&&"recipe"===window.mdManager.getPageType()&&
(0<a(".saverecipe").size()?a(".saverecipe").each(function(){var c=a(this),d=a("\x3cdiv /\x3e",{"class":"recipe-page-save-button","data-box-id":"00000149-8806-dce9-ab5f-db6f84a10007","data-box-params":JSON.stringify({assetId:mdManager.getParameter("DetailId"),showNotifications:!1,saveButtonInactiveStyleClass:"box-ss-icon box-ss-plus",saveButtonActiveStyleClass:"box-ss-icon box-ss-check",quickSaveInactiveText:"Save Recipe",quickSaveActiveText:"Saved Recipe",quickSaveActiveLinkEnabled:!1,tutorialOptions:{tutorialFinishHref:window.BOX_SERVER_HOST}}),
click:function(a){a.stopPropagation()}});d.on("savedAsset",b);c.prepend(d)}):a("#social-toolbar \x3e ul").each(function(){var c=a(this),d=a("\x3cdiv /\x3e",{"class":"recipe-page-save-button","data-box-id":"00000149-8806-dce9-ab5f-db6f84a10007","data-box-params":JSON.stringify({assetId:mdManager.getParameter("DetailId"),showNotifications:!1,saveButtonInactiveStyleClass:"box-ss-icon box-ss-plus",saveButtonActiveStyleClass:"box-ss-icon box-ss-check",quickSaveInactiveText:"Save Recipe",quickSaveActiveText:"Saved Recipe",
quickSaveActiveLinkEnabled:!1,tutorialOptions:{tutorialFinishHref:window.BOX_SERVER_HOST}}),click:function(a){a.stopPropagation()}});d.on("savedAsset",b);c.prepend(a("\x3cli /\x3e",{"class":"save",html:d}))}))}catch(q){d("Caught Error",q)}try{a(".b-panel-actions[data-panel]").each(function(){var c=a(this);if(void 0!==c.data("panel").recipeID){var d=a("\x3cdiv /\x3e",{"class":"recipe-page-save-button","data-box-id":"00000149-8806-dce9-ab5f-db6f84a10007","data-box-params":JSON.stringify({assetId:c.data("panel").recipeID,
showNotifications:!1,saveButtonInactiveStyleClass:"box-ss-icon box-ss-plus",saveButtonActiveStyleClass:"box-ss-icon box-ss-check",quickSaveInactiveText:"Save Recipe",quickSaveActiveText:"Saved Recipe",quickSaveActiveLinkEnabled:!0,tutorialOptions:{tutorialFinishHref:window.BOX_SERVER_HOST}}),click:function(a){a.stopPropagation()}});d.on("savedAsset",b);c.html(d)}})}catch(f){d("Caught Error",f)}try{void 0!==window.mdManager&&void 0!==window.mdManager.getPageType&&"recipe"===window.mdManager.getPageType()&&
a(".ingredients ul").first().append(a("\x3cdiv /\x3e",{"class":"recipe-box-shopping-list-button","data-box-id":"00000149-c08a-dc7a-a9ef-f5debbf20000","data-box-params":JSON.stringify({assetId:mdManager.getParameter("DetailId"),showNotifications:!0})}))}catch(h){d("Caught Error",h)}try{void 0!==window.mdManager&&void 0!==window.mdManager.getPageType&&"recipe"===window.mdManager.getPageType()&&a(".ingredients h6").first().siblings("ul").first().find('\x3e li[itemprop\x3d"ingredients"]').each(function(){var b=
a(this);d("Installing shopping list ingredient module on ",b);b.wrapInner('\x3cdiv class\x3d"box-block" /\x3e');b.on("click",".box-block",function(b){b=a(this).closest('[itemprop\x3d"ingredients"]').find(".recipe-box-shopping-list-ingredient-button");b.hasClass("box-selected")?b.find("a.box-active-state").trigger("click"):b.find("a.box-action-icon").trigger("click")});b.prepend(a("\x3cdiv /\x3e",{"class":"recipe-box-shopping-list-ingredient-button","data-box-id":"0000014f-707e-d6a0-a9df-7c7e290d0000",
"data-box-params":JSON.stringify({assetId:mdManager.getParameter("DetailId"),ingredient:b.text()})}))})}catch(t){d("Caught Error",t)}SNI.BOX.Util.isMobile();SNI.BOX.init()})});